#!/bin/bash
#SBATCH -p short
#SBATCH --qos=short
#SBATCH --cpus-per-task=20
#SBATCH --time=02:00:00
#SBATCH --mem-per-cpu=2500
#SBATCH --constraint=xeonib
#SBATCH --output=tmp/slurm-%A_%a.out

srun ./run-tests-20
